### ISSUE TITLE
Unhandled exception. FileHelpers.ConvertException: Error Converting '"GNR 279/2"' to type: 'Int32'.

### ISSUE THREAD

**Issue by feisti** [BergWerkGIS/convert-bev-address-data#2]
Hi Wilhelm,

Unfortunately your script is not working anymore with the latest releases.
https://www.bev.gv.at/Services/Downloads/Produktbezogene-Downloads/Unentgeltliche-Produkte/Adressregister.html

`output crs, EPSG:31287
reading street names
reading orte
reading gemeinden
reading addresses
Unhandled exception. FileHelpers.ConvertException: Error Converting '"GNR 279/2"' to type: 'Int32'.
   at FileHelpers.ConvertHelpers.Int32Converter.ParseString(String from)
   at FileHelpers.ConvertHelpers.CultureConverter.StringToField(String from)
   at FileHelpers.FieldBase.AssignFromString(ExtractedInfo fieldString, LineInfo line)
   at FileHelpers.FieldBase.ExtractFieldValue(LineInfo line)
   at FileHelpers.RecordOperations.StringToRecord(Object record, LineInfo line, Object[] values)
   at FileHelpers.FileHelperAsyncEngine`1.ReadNextRecord()
   at FileHelpers.FileHelperAsyncEngine`1.ReadNext()
   at FileHelpers.FileHelperAsyncEngine`1.AsyncEnumerator.MoveNext()
   at convert_bev_address_data.Program.Main(String[] args)`
   
   BR Christoph

**Comment by wilhelmberg** [comment]
Hi @feisti 
There a new attribute in ADRESSEN.CSV (`HNR_ADR_ZUSAMMEN`), which caused the error.
Should be fixed:
https://github.com/BergWerkGIS/convert-bev-address-data/releases

**Comment by feisti** [comment]
Hi @wilhelmberg yes it's working fine.
Thanks for the fast fix.
